app:
  port: 3000
  pub_dir: "/public"
  cookie_secret: "chicken-gangnam-style"
apis:
  base: "/apis"
  components: "/components"
files:
  index: "/static/index.html"
attributes:
  component: "data-sp-component"
  component_type: "data-sp-component-type"
  controller: "data-sp-controller"
  route: "data-sp-route"
classes:
  active: "sp-active"
  inactive: sp-inactive
  transition_active: "sp-transition-to-active"
  transition_inactive: "sp-transition-to-inactive"
